<a href="https://colab.research.google.com/github/AlexandruJutra/Pytorch_tutorial/blob/brach2/Intro_to_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
!pip list

Package                               Version
------------------------------------- -------------------
absl-py                               1.4.0
accelerate                            1.5.2
aiohappyeyeballs                      2.6.1
aiohttp                               3.11.15
aiosignal                             1.3.2
alabaster                             1.0.0
albucore                              0.0.23
albumentations                        2.0.5
ale-py                                0.10.2
altair                                5.5.0
annotated-types                       0.7.0
anyio                                 4.9.0
argon2-cffi                           23.1.0
argon2-cffi-bindings                  21.2.0
array_record                          0.7.1
arviz                                 0.21.0
astropy                               7.0.1
astropy-iers-data                     0.2025.4.14.0.37.22
astunparse                            1.6.3
atpublic                              5

In [1]:
import numpy as np

In [4]:
np1 = np.random.rand(3,4,3,3)
np1

array([[[[0.23826722, 0.20145822, 0.7632999 ],
         [0.61293857, 0.54723853, 0.07600252],
         [0.33267242, 0.56042471, 0.2232525 ]],

        [[0.43207493, 0.48718245, 0.44019692],
         [0.48974441, 0.92407095, 0.31224726],
         [0.65701572, 0.39483281, 0.31386461]],

        [[0.99210004, 0.05385041, 0.93811857],
         [0.10777853, 0.95910828, 0.36029802],
         [0.8011744 , 0.840599  , 0.57900334]],

        [[0.06188937, 0.58154974, 0.51214866],
         [0.43000833, 0.9156708 , 0.7391458 ],
         [0.50886509, 0.1290691 , 0.47738537]]],


       [[[0.05013647, 0.61826848, 0.10246601],
         [0.48521249, 0.64002753, 0.75223924],
         [0.43598592, 0.70544267, 0.28779409]],

        [[0.29521117, 0.47114794, 0.77724168],
         [0.8236512 , 0.98877971, 0.39986109],
         [0.15668015, 0.97791269, 0.5257268 ]],

        [[0.13118859, 0.93827673, 0.83205862],
         [0.13447817, 0.9695166 , 0.64232403],
         [0.00763243, 0.04862088, 0.62446614]]

In [6]:
import torch

In [7]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.2349, -0.7978, -1.3542, -0.2697],
        [ 0.8036,  0.8940,  0.8804, -0.4734],
        [ 0.6688, -0.2116, -1.4436,  1.4739]])

In [8]:
tensor_3d = torch.randn(3,4,3)

In [9]:
tensor_3d

tensor([[[-0.0203,  1.4610,  1.7127],
         [ 0.8282, -0.0319, -2.0272],
         [-0.1725,  1.1246, -0.3679],
         [ 1.2177,  0.2047, -0.8727]],

        [[ 0.7635, -0.7664, -0.3936],
         [-1.1829, -0.2601,  0.4507],
         [ 2.1157, -0.4969,  1.0957],
         [ 0.3449, -1.0539, -0.3972]],

        [[-0.3460, -0.5904, -0.2041],
         [ 0.5651,  0.7422,  1.4793],
         [ 0.7120, -1.0990, -0.6318],
         [ 0.5669, -0.3215,  0.4967]]])

In [10]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
my_torch = my_torch.reshape(2,5)

In [12]:
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
my_torch = my_torch.reshape(10)

In [14]:
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
my_torch = my_torch.reshape(2,-1)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [16]:
my_torch = torch.arange(15)
my_torch

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
my_torch = my_torch.reshape(3,-1)
my_torch

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [28]:
my_torch[:,1:3]

tensor([[ 1,  2],
        [ 6,  7],
        [11, 12]])

In [29]:
#curvustina